scss:
  enabled: false

ruby:
  enabled: false

coffeescript:
  enabled: false

jshint:
  enabled: false

scss:
  enabled: false

haml:
  enabled: false

go:
  enabled: false

swift:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore

tslint:
  enabled: true
  config_file: tslint.json

